# Generated by Django 5.2.4 on 2025-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="計畫標題")),
                ("description", models.TextField(verbose_name="計畫簡介")),
                (
                    "subject",
                    models.CharField(
                        help_text="例如：科學、藝術、語文",
                        max_length=50,
                        verbose_name="主題類別",
                    ),
                ),
                (
                    "participant_limit",
                    models.PositiveIntegerField(default=30, verbose_name="人數限制"),
                ),
                (
                    "restrictions",
                    models.TextField(
                        blank=True,
                        help_text="例如：限國中生、需自備筆電",
                        verbose_name="其他限制",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "審核中"),
                            ("approved", "已上架"),
                            ("closed", "已結束"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
        ),
    ]
