# Generated by Django 5.2.4 on 2025-07-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('university', '大學端'), ('school', '國高中小端')], max_length=20, verbose_name='使用者類別')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='計畫標題')),
                ('description', models.TextField(verbose_name='計畫簡介')),
                ('subject', models.CharField(help_text='例如：科學、藝術、語文', max_length=50, verbose_name='主題類別')),
                ('participant_limit', models.PositiveIntegerField(default=30, verbose_name='人數限制')),
                ('restrictions', models.TextField(blank=True, help_text='例如：限國中生、需自備筆電', verbose_name='其他限制')),
                ('status', models.CharField(choices=[('pending', '審核中'), ('approved', '已上架'), ('closed', '已結束')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='計畫主持人')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, verbose_name='學校聯絡人')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='聯絡 Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('notes', models.TextField(blank=True, verbose_name='備註事項')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='申請狀態')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.project', verbose_name='申請計畫')),
            ],
        ),
    ]
