# Generated by Django 5.2.4 on 2025-07-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, verbose_name='學校聯絡人')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='聯絡 Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('notes', models.TextField(blank=True, verbose_name='備註事項')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='申請狀態')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.project', verbose_name='申請計畫')),
            ],
        ),
    ]
